resources:
  - url: http://127.0.0.1:5000/flower-card.js
    type: module
views:
  - cards:
      - type: custom:flower-card
        name: Flower Development
        entity: sun.sun
        test_gui: true
